"""
COMPREHENSIVE FIX SCRIPT for app_v13.py
Run: python patch_app.py
Fixes:
  1. JSON truncation on A17, A49, A56, A81 (max_tokens too low)
  2. Location keywords being generated by A07, A81, A04, A05 (prompt fix)
  3. Better JSON repair for mid-truncation errors
  4. Strip location keywords from ALL keyword agents
"""

import re
import shutil
import os

src = "app_v13.py"
if not os.path.exists(src):
    print(f"ERROR: {src} not found in current directory!")
    exit(1)

# Backup
shutil.copy(src, "app_v13_backup_patch.py")
print(f"✅ Backed up to app_v13_backup_patch.py")

content = open(src, encoding="utf-8").read()
original = content

# ============================================================
# FIX 1: Increase max_tokens for agents that fail with JSON truncation
# A17 Campaign Architect, A49 Dayparting, A56 Lookalike, A81 KW Expander
# ============================================================

# Pattern: find ai_text calls and increase max_tokens
# We'll target specific agent functions

fixes_applied = []

def bump_tokens(content, agent_func_signature, old_tokens, new_tokens, agent_name):
    """Bump max_tokens inside a specific agent function."""
    # Find the function and replace max_tokens within it
    idx = content.find(agent_func_signature)
    if idx == -1:
        print(f"  ⚠️  Could not find function for {agent_name}")
        return content, False
    
    # Find the next ai_text call after this function
    next_aitext = content.find("ai_text(", idx)
    if next_aitext == -1:
        return content, False
    
    # Get a window of ~300 chars around the ai_text call to find max_tokens
    window_end = min(next_aitext + 500, len(content))
    window = content[next_aitext:window_end]
    
    new_window = window.replace(f"max_tokens={old_tokens}", f"max_tokens={new_tokens}", 1)
    if new_window != window:
        content = content[:next_aitext] + new_window + content[window_end:]
        fixes_applied.append(f"  ✅ {agent_name}: max_tokens {old_tokens} → {new_tokens}")
        return content, True
    return content, False


# ============================================================
# FIX 2: Better JSON repair function - replace the existing one
# ============================================================

old_repair = '''def repair_json(text):
    """Try to repair truncated JSON."""'''

new_repair = '''def repair_json(text):
    """Try to repair truncated JSON - handles mid-truncation and bad commas."""'''

# More comprehensive repair - find and replace the entire repair_json function
repair_func_start = content.find("def repair_json(")
if repair_func_start != -1:
    # Find end of function (next def at same indent level)
    repair_func_end = content.find("\ndef ", repair_func_start + 10)
    if repair_func_end == -1:
        repair_func_end = content.find("\nasync def ", repair_func_start + 10)
    
    new_repair_func = '''def repair_json(text):
    """
    Comprehensive JSON repair:
    - Handles truncated responses (unclosed strings/arrays/objects)
    - Handles 'Expecting , delimiter' (missing commas)
    - Handles 'Expecting value' (trailing commas before closing bracket)
    """
    if not text or not text.strip():
        return None
    
    text = text.strip()
    
    # Remove markdown code fences
    text = re.sub(r'^```(?:json)?\s*', '', text, flags=re.MULTILINE)
    text = re.sub(r'\s*```$', '', text, flags=re.MULTILINE)
    text = text.strip()
    
    # Try direct parse first
    try:
        return json.loads(text)
    except Exception:
        pass
    
    # Fix 1: Remove trailing commas before ] or }
    cleaned = re.sub(r',\s*([}\]])', r'\1', text)
    try:
        return json.loads(cleaned)
    except Exception:
        pass
    
    # Fix 2: Find the last complete JSON object/array
    # Try truncating at different points
    for end_char in ['}', ']']:
        last_pos = cleaned.rfind(end_char)
        while last_pos > 0:
            candidate = cleaned[:last_pos + 1]
            # Balance brackets
            opens = candidate.count('{') - candidate.count('}')
            opens_arr = candidate.count('[') - candidate.count(']')
            if opens == 0 and opens_arr == 0:
                try:
                    return json.loads(candidate)
                except Exception:
                    pass
            last_pos = cleaned.rfind(end_char, 0, last_pos)
    
    # Fix 3: Auto-close open structures
    fixed = cleaned
    # Close unclosed strings
    in_string = False
    escaped = False
    for i, c in enumerate(fixed):
        if escaped:
            escaped = False
            continue
        if c == '\\\\':
            escaped = True
            continue
        if c == '"':
            in_string = not in_string
    if in_string:
        fixed += '"'
    
    # Count unmatched brackets/braces
    opens = fixed.count('{') - fixed.count('}')
    opens_arr = fixed.count('[') - fixed.count(']')
    
    # Remove trailing comma before closing
    fixed = re.sub(r',\s*$', '', fixed.rstrip())
    fixed += ']' * max(0, opens_arr) + '}' * max(0, opens)
    
    try:
        return json.loads(fixed)
    except Exception:
        pass
    
    # Fix 4: Extract just the first complete top-level object
    match = re.search(r'\{[^{}]*\}', cleaned)
    if match:
        try:
            return json.loads(match.group())
        except Exception:
            pass
    
    return None

'''
    
    if repair_func_end != -1:
        content = content[:repair_func_start] + new_repair_func + content[repair_func_end:]
        fixes_applied.append("  ✅ repair_json() replaced with comprehensive version")
    else:
        fixes_applied.append("  ⚠️  Could not replace repair_json (end not found)")
else:
    fixes_applied.append("  ⚠️  repair_json() not found - inserting new version")
    # Insert before ai_text function
    insert_point = content.find("def ai_text(")
    if insert_point != -1:
        new_repair_func = '''def repair_json(text):
    """Comprehensive JSON repair."""
    if not text or not text.strip():
        return None
    text = text.strip()
    text = re.sub(r'^```(?:json)?\\s*', '', text, flags=re.MULTILINE)
    text = re.sub(r'\\s*```$', '', text, flags=re.MULTILINE)
    text = text.strip()
    try:
        return json.loads(text)
    except Exception:
        pass
    cleaned = re.sub(r',\\s*([}\\]])', r'\\1', text)
    try:
        return json.loads(cleaned)
    except Exception:
        pass
    fixed = cleaned
    opens = fixed.count('{') - fixed.count('}')
    opens_arr = fixed.count('[') - fixed.count(']')
    fixed = re.sub(r',\\s*$', '', fixed.rstrip())
    fixed += ']' * max(0, opens_arr) + '}' * max(0, opens)
    try:
        return json.loads(fixed)
    except Exception:
        return None


'''
        content = content[:insert_point] + new_repair_func + content[insert_point:]
        fixes_applied.append("  ✅ repair_json() inserted before ai_text()")


# ============================================================
# FIX 3: Add location keyword prohibition to ALL keyword agent prompts
# ============================================================

NO_LOCATION_INSTRUCTION = """
CRITICAL KEYWORD RULES - STRICTLY FOLLOW:
1. NEVER include location-specific keywords (NO city names, state names, zip codes)
2. NEVER include "near me", "nearby", "local", "in [city]", "around me", "[city] fl", "[city] ca" etc.
3. Location targeting is handled SEPARATELY in campaign geo-settings, NOT in keywords
4. Only include SERVICE-BASED keywords (what the service is, not where)
BAD examples: "pool cleaning clearwater fl", "pool service near me", "local pool repair"
GOOD examples: "pool cleaning service", "pool repair", "pool maintenance"
"""

# Find keyword-related agent functions and inject the instruction
keyword_agent_markers = [
    ("def run_agent_04(", "STAG keyword", "generate.*keyword|keyword.*list|search terms"),
    ("def run_agent_05(", "brand segmentation", "keyword|search term"),
    ("def run_agent_07(", "intent cluster", "keyword|search intent"),
    ("def run_agent_81(", "KW expander", "keyword|expand"),
    ("def run_agent_82(", "KW gap", "keyword|gap"),
]

for func_sig, agent_desc, _ in keyword_agent_markers:
    idx = content.find(func_sig)
    if idx == -1:
        print(f"  ⚠️  Function {func_sig} not found")
        continue
    
    # Find the prompt string within this function
    # Look for the main prompt (usually starts with triple quote or f-string after 'prompt =' or 'messages =')
    func_end = content.find("\nasync def ", idx + 10)
    if func_end == -1:
        func_end = content.find("\ndef ", idx + 10)
    if func_end == -1:
        func_end = idx + 5000
    
    func_body = content[idx:func_end]
    
    # Check if already has NO_LOCATION
    if "NEVER include location" in func_body or "NO city names" in func_body:
        fixes_applied.append(f"  ℹ️  {func_sig}: location instruction already present")
        continue
    
    # Find the first triple-quoted string in this function (the prompt)
    prompt_start = func_body.find('"""')
    if prompt_start == -1:
        prompt_start = func_body.find("'''")
        quote = "'''"
    else:
        quote = '"""'
    
    if prompt_start == -1:
        fixes_applied.append(f"  ⚠️  {func_sig}: no triple-quoted prompt found")
        continue
    
    # Find end of this string
    str_end = func_body.find(quote, prompt_start + 3)
    if str_end == -1:
        fixes_applied.append(f"  ⚠️  {func_sig}: prompt string not closed")
        continue
    
    # Inject before the closing triple quote
    inject_text = f"\n{NO_LOCATION_INSTRUCTION}\n"
    new_func_body = func_body[:str_end] + inject_text + func_body[str_end:]
    content = content[:idx] + new_func_body + content[idx + len(func_body):]
    fixes_applied.append(f"  ✅ {func_sig}: NO-LOCATION instruction injected into prompt")


# ============================================================
# FIX 4: Increase max_tokens for specific failing agents
# Find all ai_text calls and increase for known failing agents
# ============================================================

# Strategy: find each agent function and bump its max_tokens
agent_token_fixes = {
    "run_agent_17": ("Campaign Architect", 900, 3000),
    "run_agent_49": ("Dayparting", 700, 2500),
    "run_agent_56": ("Lookalike", 700, 2500),
    "run_agent_81": ("KW Expander", 900, 2000),
    "run_agent_82": ("KW Gap", 700, 2000),
    "run_agent_09": ("PMax Assets", 1500, 2500),
    "run_agent_27": ("Landing Pages", 1400, 2500),
    "run_agent_08": ("RSA Copywriter", 1500, 2500),
}

for func_name, (agent_desc, old_tok, new_tok) in agent_token_fixes.items():
    func_sig = f"def {func_name}("
    idx = content.find(func_sig)
    if idx == -1:
        func_sig = f"async def {func_name}("
        idx = content.find(func_sig)
    if idx == -1:
        fixes_applied.append(f"  ⚠️  {func_name} not found")
        continue
    
    func_end = content.find("\nasync def ", idx + 10)
    if func_end == -1:
        func_end = content.find("\ndef ", idx + 10)
    if func_end == -1:
        func_end = idx + 8000
    
    func_body = content[idx:func_end]
    
    # Replace max_tokens in this function
    changed = False
    for tok_val in [str(old_tok), "700", "900", "1000", "1400", "1500"]:
        if f"max_tokens={tok_val}" in func_body:
            new_func = func_body.replace(f"max_tokens={tok_val}", f"max_tokens={new_tok}", 1)
            if new_func != func_body:
                content = content[:idx] + new_func + content[idx + len(func_body):]
                fixes_applied.append(f"  ✅ {agent_desc} ({func_name}): max_tokens → {new_tok}")
                changed = True
                break
    
    if not changed:
        # Check if it already has high tokens
        tok_match = re.search(r'max_tokens=(\d+)', func_body)
        if tok_match:
            current = int(tok_match.group(1))
            if current >= new_tok:
                fixes_applied.append(f"  ℹ️  {agent_desc}: already has max_tokens={current}")
            else:
                # Force replace whatever value is there
                new_func = re.sub(r'max_tokens=\d+', f'max_tokens={new_tok}', func_body, count=1)
                content = content[:idx] + new_func + content[idx + len(func_body):]
                fixes_applied.append(f"  ✅ {agent_desc}: max_tokens {current} → {new_tok}")
        else:
            fixes_applied.append(f"  ⚠️  {agent_desc}: no max_tokens found in function")


# ============================================================
# FIX 5: Ensure import re and import json are at the very top
# ============================================================

# Check for import re
if "import re\n" not in content[:500] and "import re " not in content[:500]:
    # Add after first import statement
    first_import = content.find("import ")
    if first_import != -1:
        line_end = content.find("\n", first_import)
        content = content[:line_end+1] + "import re\n" + content[line_end+1:]
        fixes_applied.append("  ✅ Added 'import re' to top of file")
else:
    fixes_applied.append("  ℹ️  import re already present")

# ============================================================
# FIX 6: Aggressive _strip_location_keywords replacement  
# ============================================================

old_strip_start = content.find("def _strip_location_keywords(")
if old_strip_start != -1:
    old_strip_end = content.find("\ndef ", old_strip_start + 10)
    if old_strip_end == -1:
        old_strip_end = content.find("\nasync def ", old_strip_start + 10)
    
    new_strip_func = '''def _strip_location_keywords(kw_data, target_location=""):
    """
    AGGRESSIVELY remove location-specific keywords from any keyword structure.
    Handles: lists, dicts, nested objects, strings.
    """
    # Build location patterns to strip
    location_patterns = [
        r'\\bnear me\\b', r'\\bnearby\\b', r'\\blocal\\b', r'\\bin my area\\b',
        r'\\baround me\\b', r'\\bin my city\\b', r'\\bin [a-z]+ (fl|ca|tx|ny|az|ga|nc|va|wa|or|co|nv|ut|id|mt|wy|nd|sd|ne|ks|ok|ar|la|ms|al|tn|ky|wv|sc|mo|ia|mn|wi|il|in|mi|oh|pa|nj|de|md|ct|ri|ma|vt|nh|me|ak|hi)\\b',
        r'\\b[a-z]+(\\s[a-z]+)? (fl|ca|tx|ny|az|ga|nc|va|wa|or|co|nv|ut|id|mt|wy|nd|sd|ne|ks|ok|ar|la|ms|al|tn|ky|wv|sc|mo|ia|mn|wi|il|in|mi|oh|pa|nj|de|md|ct|ri|ma|vt|nh|me|ak|hi)\\b',
    ]
    
    # Extract city/state from target_location if provided
    if target_location:
        # Split "City, State" or "City State" 
        parts = re.split(r'[,\\s]+', target_location.lower().strip())
        for part in parts:
            part = part.strip()
            if len(part) > 2:  # Skip short abbreviations
                location_patterns.append(r'\\b' + re.escape(part) + r'\\b')
    
    def is_location_keyword(kw_str):
        """Return True if keyword contains location terms."""
        kw_lower = kw_str.lower().strip()
        for pattern in location_patterns:
            if re.search(pattern, kw_lower):
                return True
        return False
    
    def strip_from_list(kw_list):
        """Remove location keywords from a list."""
        if not isinstance(kw_list, list):
            return kw_list
        result = []
        for item in kw_list:
            if isinstance(item, str):
                if not is_location_keyword(item):
                    result.append(item)
            elif isinstance(item, dict):
                result.append(strip_from_dict(item))
            else:
                result.append(item)
        return result
    
    def strip_from_dict(d):
        """Recursively strip location keywords from dict values."""
        if not isinstance(d, dict):
            return d
        result = {}
        for k, v in d.items():
            if k.lower() in ('keyword', 'keywords', 'search_terms', 'terms', 'kws', 'kw_list', 'keyword_list'):
                if isinstance(v, list):
                    result[k] = strip_from_list(v)
                elif isinstance(v, str):
                    result[k] = v if not is_location_keyword(v) else ""
                else:
                    result[k] = v
            elif isinstance(v, list):
                result[k] = strip_from_list(v)
            elif isinstance(v, dict):
                result[k] = strip_from_dict(v)
            else:
                result[k] = v
        return result
    
    # Handle different input types
    if isinstance(kw_data, list):
        return strip_from_list(kw_data)
    elif isinstance(kw_data, dict):
        return strip_from_dict(kw_data)
    elif isinstance(kw_data, str):
        return kw_data if not is_location_keyword(kw_data) else ""
    return kw_data

'''
    
    if old_strip_end != -1:
        content = content[:old_strip_start] + new_strip_func + content[old_strip_end:]
        fixes_applied.append("  ✅ _strip_location_keywords() completely rewritten - now handles nested objects")
    else:
        fixes_applied.append("  ⚠️  _strip_location_keywords: could not find end of function")
else:
    fixes_applied.append("  ⚠️  _strip_location_keywords not found - not replacing")


# ============================================================
# Write fixed file
# ============================================================

if content == original:
    print("\n⚠️  WARNING: No changes were made to the file!")
    print("The function signatures may be different in your version.")
else:
    open(src, "w", encoding="utf-8").write(content)
    print(f"\n✅ Fixed file written to {src}")

print("\n📋 All fixes applied:")
for fix in fixes_applied:
    print(fix)

# Verify no syntax errors with Python
import subprocess
result = subprocess.run(["python", "-m", "py_compile", src], capture_output=True, text=True)
if result.returncode == 0:
    print(f"\n✅ Python syntax check PASSED on {src}")
else:
    print(f"\n❌ Python syntax error detected:")
    print(result.stderr)
    print(f"\nRestoring backup...")
    shutil.copy("app_v13_backup_patch.py", src)
    print("Backup restored. No changes applied.")
